### ISSUE TITLE
Put the dataset in a more friendly format

### ISSUE THREAD

**Issue by gregmacfarlane** [sidharthanr/macml#6]
See `data/data.R` for the existing documentation on the dataset. Are these synthetic data, or do they come from somewhere? If they are real, what is the interpretation of the variables?

The documentation might be easier to write/understand if the dataset is moved to id-case/id-alt format (_long_), where each row is an alternative and each choice maker has several rows. If the data must be
in wide format for processing, we can handle that behind the scenes.

**Comment by sidharthanr** [comment]
Okay. The original data was synthetic and were in a _wide_ format. Long data is easier to specify if the number of alternative specific (AS) variables is small and the number of alternatives is small, otherwise the dataset becomes cumbersome. For example, in an MNL model for Work-start+Work-end model for SCAG we had 2000+ alternatives and 100+ AS variables. This will make dataset unwieldy in a long format. 

But I agree that for a beginner user long data format is easier to understand. We can work towards supporting both formats.

Among common estimation software, SAS supports long data exclusively but others like Biogeme, Alogit supports wide data exclusively.

**Comment by gregmacfarlane** [comment]
I think that long formats follow the principle of [tidy data](http://www.jstatsoft.org/v59/i10/paper), and wide formats do not. Behind the scenes `dplyr` makes it really easy to switch from one to the other, so if our code only works on `wide`, we can have a check to convert it.

**Comment by sidharthanr** [comment]
Yes, that should be possible.
